### ISSUE TITLE
创建课程时闪退

### ISSUE THREAD

**Issue by Pxl726** [dujiajun/CourseBlock#4]
日志如下，miui13 Android12 红米k50
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dujiajun.courseblock/com.dujiajun.courseblock.CourseActivity}: java.lang.ArrayIndexOutOfBoundsException: length=22; index=24
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3949)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)

**Comment by w1049** [comment]
可以检查一下学期起始日设置是否正确

**Comment by Pxl726** [comment]
https://github.com/dujiajun/CourseBlock/issues/4#issuecomment-1236365313多谢
